### ISSUE TITLE
Value restrictions in FrSexEst

### ISSUE THREAD

**Issue by MasterChief13** [RDFBones/FrSexEst#10]
This is a list of all triples with value restrictions that are part of FrSexEst.
It makes sense to keep track of all value restrictions since Vitro does not evaluate value restrictions correctly. Therefore, we shoud discuss what to do in all these cases.
The „X“ in severel lines indicates that triples of this kind exist for each evaluated trait (Glabella, MastoidProcess etc.). So there are in total 14 triples of this kind.

In the following, all triples with value restrictions that are formulated in the correct direction according to the Wiki pages are listed. „Correct direction“ means that the Investigation should have a „has part“-relation to the StudyDesign, while the partonomy relation „StudyDesign is part of Investigation“ is formulated in the wrong direction according to the Wiki pages (see below).
- planning.FrSexEst 'has specified output' value StudyDesign.FrSexEst
- Investigation.FrSexEst 'has part' value StudyDesign.FrSexEst
- SpecimenCollectionProcess.X 'achieves planned objective' value SpecimenCollectionObjective.X
- DataTransformation.FrSexEst 'achieves planned objective' value DataTransformationObjective.FrSexEst

In case of the following triples, the value restriction was used because Protege does not allow references from instances to classes. That is, these triples are formulated in the opposite direction as the Wiki pages suggest. If Cuboideum has some free time left, please correct these cases directly in the XML-code. Then we can omit the "inverse IsAbout'-property.
- Plan.FrSexEst 'concretizes' value StudyDesignFrSexEst
- SpecimenCollectionProcess.X 'inverse IsAbout' value SkeletalMaterialRequirement.X
- SexScore 'inverse IsAbout' value SpecificationOfDataToBeGenereatedInAnInvestigation.FrSexEst
- DegreeOfSexualization 'inverse IsAbout' value SpecificationOfDataToBeGenereatedInAnInvestigation.FrSexEst
- EstimatedSex 'inverse IsAbout' value SpecificationOfDataToBeGenereatedInAnInvestigation.FrSexEst
- Specimen.X 'bearer of' value SexEstimation (subclass of 'Evaluant role')
- Assay.X 'realizes' value SexEstimation
- Assay.X 'inverse IsAbout' AssaySpecification.X

**Comment by cuboideum** [comment]
> - Plan.FrSexEst 'concretizes' value StudyDesignFrSexEst

Individual 'StudyDesignFrSexEst' is used for each investigation carried out with this study design, instances of class 'Plan.FrSexEst' are unique to each such investigation. I would say, the declaration can be left as is.

**Comment by cuboideum** [comment]
After adding 'is about' statments to instances of classes 'SkeletalMaterialRequirement.X and deleting the inverse statements with 'inverse IsAbout', it seems that Protégé accepts these better than expected. The statements are not interpreted as annotations but properly displayed along property relations with other individuals. They are also displayed in the 'Object Property Usage' tab of property obo:IAO_0000136 ('is about'). However, they do not appear in the 'Class Usage' tab of related classes 'SpecimenCollectionProcess.X'.

**Comment by cuboideum** [comment]
> - Specimen.X 'bearer of' value SexEstimation (subclass of 'Evaluant role')
> - Assay.X 'realizes' value SexEstimation

Several types of specimen, in the context of various types of investigations, will be created with the intent to carry out a sex estimation. The same goes for assays. It is comparatively unlikely that one assay type will take on several evaluant roles, though this is not inconceivable. With specimen types it is more likely that they will satisfy several evaluant roles. However, the evaluant role still is the best candidate among them in terms of universality. As a consequence, I would leave the statrments as they are.

**Comment by cuboideum** [comment]
I have created the relations with individuals in the domain and classes in the range (for exceptions see comments above). @zarquon42b tested if the resulting file could be loaded into VIVO. This was possible without complaints from the VITRO reasoner.

As my part of the job is done, I remove myself from the list of assignees.

**Comment by MasterChief13** [comment]
Problems solved
