### ISSUE TITLE
Inconsistent naming of elements

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/FrSexEst#14]
The following groups of classes and instances are named inconsistently, with some of the names containing the extension name 'FRSexEst' and other not.
- subclasses of obo:OBI_0000659 ('Specimen collection process')
- individuals of class rdfbones:SkeletalMaterialRequirement
- subclasses of obo:OBI_0100051 ('Specimen')
- subclasses of obo:OBI_0000070 ('Assay')
- individuals of class obo:OBI_0001896 ('Investigation assay specification')

Please check, if these inconsistencies also affect other groups of elements.

**Comment by MasterChief13** [comment]
This is true for all classes related to the trait "ZygomaticArch". The zygomatic arch is not part of the method for sex estimation according to Ferembach et al. 1979, so I regard the zygomatic arch as being specifically and exclusively part of the Freiburg method. Therefore, naming is different in this case but not inconsistent.

**Comment by cuboideum** [comment]
Fair point.
