### ISSUE TITLE
Second Data transformation missing

### ISSUE THREAD

**Issue by zarquon42b** [RDFBones/FrSexEst#30]
The extension is lacking the data transformation, transforming the multiple single floats (assigned in the existing one) to one final summarizing value, e.g. a sexualization score of 1.3.

**Comment by MasterChief13** [comment]
I propose an enhanced version in pull request #31.

The final output, i.e. the DegreeOfSexualization, is now obtained in three steps:
1) Data collection (for instance, add label "feminine" to SexScore.Glabella)
2) Calculation of weighted SexScores ("feminine" -> -1 and -1 * 3[weight for Glabella] = -3)
3) Calculation of DegreeOfSexualization (-3 / 3 = -1)

The corresponding triples for each step are:
1) Data collection
Assay.X 'has specified output' exactly 1 Sex.Score.X

2) Calculating weighted SexScores for each trait
DataTransformation.X 'has specified input' exactly 1 SexScore.X
DataTransformation.X 'has specified output' exactly 1 WeightedSexScore.X

3) Calculating DegreeOfSexualization
DataTransformation.DegreeOfSexualization 'has specified input' exactly 1 WeightedSexScore.X [for X traits]
DataTransformation.DegreeOfSexualization 'has specified output' exactly 1 DegreeOfSexualization

Is this explicit enough? We could also split step 2) in two different processes: assigning numbers to labels and then multiplying the number with the respective weight. Personally, I don't think that this necessary.

**Comment by MasterChief13** [comment]
I close this issue since the solution described above was accepted some time ago.
