### ISSUE TITLE
Incorrect property by restriction on scalar measurement datums

### ISSUE THREAD

**Issue by kdaveed** [RDFBones/FrSexEst#34]
@MasterChief13 
You use the property http://vivoweb.org/ontology/core#hasValue by the classes : *DegreeOfSexualization* and *WeightedSexScore*. But based on the [article](https://github.com/RDFBones/RDFBones-O/wiki/Data-in-OBI) I believe it should be the obo:IAO_0000004 **"has measurement value**" property.

**Comment by MasterChief13** [comment]
The problem is that _'has measurement value'_ has _xsd:float_ as range. Thus, I cannot use this property for the weighted sex scores - they are by definition integers (-6; -4; -2; -1; 0; 1; 2; 4; 6). That is why I decided to use _'has value'_ because I can define its range as I need it. We should discuss this in our next project meeting.

**Comment by cuboideum** [comment]
This is the presentation file that we discussed in the project meeting today:

[DFG-Standards_ProjectMeeting_2017-03-14.pdf](https://github.com/RDFBones/FrSexEst/files/840760/DFG-Standards_ProjectMeeting_2017-03-14.pdf)

We agreed, for now, to use the existing subclasses of obo:IAO_0000109 ('Measurement datum'): obo:IAO_0000032 ('Scalar measurement datum') and obo:OBI_0000938 ('Categorical measurement datum'). @MasterChief13 will include a list of caveats in the documentation of his extensions, including the need for implementation of additional levels of measurement in the RDFBones core ontology.

**Comment by cuboideum** [comment]
I have opened the [RDFBones issue #108](https://github.com/RDFBones/RDFBones-O/issues/108) to record implementation of levels of measurement as a feature request for the future development of the RDFBones core ontology.
