### ISSUE TITLE
Drawing a conclusion is not in a direct part_of relationship to Investigation

### ISSUE THREAD

**Issue by zarquon42b** [RDFBones/FrSexEst#37]
Drawing a conclusion is not in a direct part_of relationship to Investigation:
https://github.com/RDFBones/FrSexEst/blob/master/ExtensionFrSexEst.owl#L1625 please check out the documentation: https://github.com/RDFBones/RDFBones-O/wiki/Investigation-execution.

**Comment by cuboideum** [comment]
THIS IS AN APOLOGY
###################
After having misinformed @zarquon42b that obo:OBI_0000338 ('drawing a conclusion based on data') was part of obo:OBI_0000471 ('Study design execution'), I have to find out that **this is not the case**. Please note that drawing a conclusion based on data is directly asserted to be part of an investigation (obo:OBI_0000066).

This is not yet documented in the [RDFBones-O wiki](https://github.com/RDFBones/RDFBones-O/wiki) but an overview graph is on the [OBI core ontology webpage](http://obi-ontology.org/page/Core):

![OBI core ontology](http://obi-ontology.org/w/images/thumb/9/97/OBI-core.jpg/1000px-OBI-core.jpg)

@MasterChief13: Your extension was correct.
@kdaveed: Your decision to put conclusions on the investigation profile page was right.
